name: deploy-stage

on:
  workflow_run:
    workflows: ["node-ci-workflow"]
    types:
      - completed

jobs:
  deploy: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/testbot
            git pull
            npm install
            npm run build
            pm2 restart testbot
